### ISSUE TITLE
Add support for gitlab CI runner environment

### ISSUE THREAD

**Issue by daurnimator** [moteus/luacov-coveralls#12]
See https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables

Currently fails as unknown: https://gitlab.com/daurnimator/lua-http/-/jobs/85046313

**Comment by daurnimator** [comment]
Btw, instead of defaulting to nothing; lets use the env vars that coveralls recommends: https://docs.coveralls.io/supported-ci-services

**Comment by moteus** [comment]
Can you please checkout `gitlab_ci` branch to confirm that it works.
