### ISSUE TITLE
Coveralls fails to show files

### ISSUE THREAD

**Issue by hishamhm** [moteus/luacov-coveralls#2]
First of all, thank you for this plugin! Integrating Coveralls support for LuaRocks+Travis CI was a breeze!

I just noticed something strange. When I click on a filename, Coveralls gives me an error message:

https://coveralls.io/builds/2294176/source?filename=%2Fhome%2Ftravis%2Fbuild%2Fkeplerproject%2Fluarocks%2Fsrc%2Fluarocks%2Ftools%2Fpatch.lua

> "Source Not Available"
> The file "/home/travis/build/keplerproject/luarocks/src/luarocks/tools/patch.lua" isn't available on GitHub.
> Either it's been removed, or the repo root directory needs to be updated.

Perhaps the prefix "/home/travis/build/keplerproject/luarocks/" should be stripped out of the pathnames when sending the data to coveralls.io? I wonder if the plugin could do this automatically.

**Comment by moteus** [comment]
Yes. Use `pathcorect` option. Checkout this [example](https://github.com/moteus/lua-travis-example/blob/master/test/.luacov#L45)

**Comment by moteus** [comment]
@hishamhm ping
