### ISSUE TITLE
There's a question about github action's problem

### ISSUE THREAD

**Issue by JeremyRenjw** [moteus/luacov-coveralls#22]

**Comment by renjiawei0401** [comment]
@alerque

**Comment by renjiawei0401** [comment]
@leandromoreira @blueyed @fperrad

**Comment by alerque** [comment]
I'm sorry but I don't understand what your question or problem is. Can you be more specific about what project you are referring to, how you have it setup, and where you see a problem? You've pinged a bunch of people but there isn't enough information in this issue report to be answerable.

**Comment by renjiawei0401** [comment]
> I'm sorry but I don't understand what your question or problem is. Can you be more specific about what project you are referring to, how you have it setup, and where you see a problem? You've pinged a bunch of people but there isn't enough information in this issue report to be answerable.
