### ISSUE TITLE
Fails on Windows with Lua 5.4

### ISSUE THREAD

**Issue by Tieske** [moteus/luacov-coveralls#26]
The failure is related to `lua-path`, which has platform specific code. See https://ci.appveyor.com/project/Tieske/penlight/builds/34814130/job/tum1pf3gm3eyh6jr

Though I'm not sure whether the fix should be here or in `lua-path`

**Comment by Tieske** [comment]
I had to put in a workaround; https://github.com/lunarmodules/Penlight/blob/59dc58abbea8b16cb28012fae23fb41a4147a84c/appveyor.yml#L22

If just installing "bit32" then LuaRocks would complain that it was natively present in the Lua engine (for Lua 5.2 and Lua 5.3), so had to wrap it in an if statement to only install on Lua 5.4.

BTW: @hishamhm is that a LuaRocks issue?

**Comment by alerque** [comment]
@Tieske Yes I think this is a LuaRocks issue, I reported it here: https://github.com/luarocks/luarocks/issues/1204

**Comment by hishamhm** [comment]
Just pushed a PR to @alerque's issue https://github.com/luarocks/luarocks/pull/1218

The weird bit here is why Lua _5.4_ is failing with this.

**Comment by moteus** [comment]
Is it valid issue?
lua-path uses bit32 library only up to Lua 5.3. On Lua 5.3 and newer it uses bit operations.
So not sure how it can be broken by Lua 5.4

**Comment by Tieske** [comment]
This was fixed by luarocks.

workaround removal here: https://github.com/lunarmodules/Penlight/pull/375

**Comment by Tieske** [comment]
thx @hishamhm @alerque @moteus for looking into it.
