### ISSUE TITLE
How to use it with Github Actions

### ISSUE THREAD

**Issue by devkapilbansal** [moteus/luacov-coveralls#27]
Hi, I want to use this with my Github CI build. I get repo-token from coveralls that I kept in my environment secrets.
But the buid is failing giving the following error:
```
/usr/bin/lua5.1: .../rocks/luacov-coveralls/0.2.3-1/bin/luacov-coveralls:64: assertion failed!
stack traceback:
	[C]: in function 'assert'
	.../rocks/luacov-coveralls/0.2.3-1/bin/luacov-coveralls:64: in function 'read_key'
	.../rocks/luacov-coveralls/0.2.3-1/bin/luacov-coveralls:93: in main chunk
	[C]: ?
```

Here is the link to the build workflow:- https://github.com/devkapilbansal/openwrt-openwisp-monitoring/runs/3045353380?check_suite_focus=true

Can you please provide instructions in README for github actions too similar to travis?

**Comment by alerque** [comment]
Here is an example in use:

https://github.com/sile-typesetter/cassowary.lua/blob/master/.github/workflows/busted.yml

**Comment by devkapilbansal** [comment]
Hi @alerque I tried doing similar but still the build fails
https://github.com/devkapilbansal/openwrt-openwisp-monitoring/runs/3046476515?check_suite_focus=true

Can you please help debug it?

**Comment by devkapilbansal** [comment]
Thanks a lot, it helps
