### ISSUE TITLE
Support for Drone.io

### ISSUE THREAD

**Issue by telemachus** [moteus/luacov-coveralls#3]
I've been using luacov-coveralls without any trouble on [Drone.io](https://drone.io/).

It's pretty straightfoward:
- Install luacov and luacov-coveralls as part of the build process.
- Add `COVERALLS_REPO_TOKEN=<TOKEN>` to your repo's Settings under Environment Variables.
- Call `luacov-coveralls -t "$COVERALLS_REPO_TOKEN"` at the end of the build.

I'm wondering what else you might want to do to test Drone.io builds and whether you'd accept a pull request to add these instructions to the README.

Thanks.

**Comment by moteus** [comment]
You do not need set `-t` switch. luacov-coveralls checked COVERALLS_REPO_TOKEN env variable by default.
Also COVERALLS_REPO_TOKEN should be encrypded if it stored in repo.
I tested luacov-coveralls also on CodeShip and it works well.

**Comment by telemachus** [comment]
> You do not need set -t switch. luacov-coveralls checked COVERALLS_REPO_TOKEN env variable by default.

Ah, cool. I don't store the token in the repo. I only store it at Drone.io as an environment variable. It isn't visible to anyone not logged into my account.

> I tested luacov-coveralls also on CodeShip and it works well.

Ah, ok. The README still says "This module tested only on Travis-CI." So I was hoping to update that with whatever brief instructions were necessary for Drone.io (and CodeShip too maybe).
