### ISSUE TITLE
Pathcorrect doesn't merge coverage

### ISSUE THREAD

**Issue by psychon** [moteus/luacov-coveralls#4]
Hi,

I'm in the process of adding coverage testing to awesome. Thanks for writing this code!
However, due to $REASONS there are two kind of tests in awesome. One of them runs through `busted` and ends up with absolute paths to the Lua source files while the other one has relative paths. With `pathcorrect` the paths end up correctly in the end, but LuaCov/Coveralls still counts these as two different files.

For an example look at https://coveralls.io/jobs/11825631 and search for files with "sort" in their name. Two instances of `lib/gears/sort.lua` will be found and they have different coverage.

Is there a sane way to have these duplicate files merged?

Thanks!

**Comment by moteus** [comment]
Can you test current master please.

**Comment by psychon** [comment]
Thanks, works fine!
https://github.com/awesomeWM/awesome/commit/0af8729ce491ee92e40c4ba9fb77948ff51b9d99
https://coveralls.io/jobs/11854348

**Comment by moteus** [comment]
Just release new version.
