### ISSUE TITLE
bugs in version 0.2.0

### ISSUE THREAD

**Issue by starius** [moteus/luacov-coveralls#5]
Following on from https://github.com/moteus/luacov-coveralls/issues/1

> This build/job looks ok. May be it was glitch in coveralls service.

I removed recent reports from coveralls, reauthorize coveralls on GitHub. Then in several hours the empty reports have been filling themselves.

I tried again https://github.com/npge/lua-npge/pull/20 (with luacov-coveralls 0.2.0 and dkjson).

It produced two coveralls reports:
- [332](https://coveralls.io/builds/5060141), Travis, empty coverage;
- [140](https://coveralls.io/builds/5060145), AppVeyor, unbound from the pull request.

Both reports have problems, so coveralls did not report the coverage to GitHub ("Waiting for status to be reported").

> luacov-coveralls will use cjson if it can find it. so you can just install it.

Can you always use dkjson, please? More options, more bugs...

> Could you please try again 2.0 with dkjson and with cjson.

I have just committed https://github.com/npge/lua-npge/commit/fd3ec1e3e02e833f65ebb4a5c97d002978aa0cba (install lua-cjson in Travis before luacov-coveralls):
- [333](https://coveralls.io/builds/5068222), Travis, good.
- [141](https://coveralls.io/builds/5067859), AppVeyor, similar to 140.

**Comment by moteus** [comment]
Seems it some related with dkjson. May be it has problem with decode generated json report from cpp-coveralls. I test with `luajson` library and it seems works ok. May be i just add one more rockspec to luacov-coveralls.

**Comment by starius** [comment]
I have installed luajson before luacov-coveralls and it seems to work. I have [dumped c.report.json](https://pasta.cf/warm-brain-especially/raw/c.report.json) in Travis, so you can test parsing in dkjson.

Can you make coveralls provide link to AppVeyor build, as it does for Travis builds?
Example:
https://coveralls.io/builds/5077736
https://coveralls.io/builds/5078283

**Comment by moteus** [comment]
Found a problem in `dkjson`
This is example

``` Lua
local json = require "dkjson"
local str = "[" .. ("null,"):rep(100) .. "0" .. (",null"):rep(100) .. "]"
local inp = assert(json.decode(str))
local out = json.encode(inp):gsub("%s", "")
assert(str == out, out) -- error {"101":0}
```

`dkjson` produce object instead of array.  (cjson and luajson pass test)
I think I create new rockspec tomorrow.
Thanks to test data.

> Can you make coveralls provide link to AppVeyor build, as it does for Travis builds?

This is not me. `luacov-coveralls` send exactly same json from Travis and from AppVeyor. (from appveyor It only also send `service_number`)
I can send only info described [here](https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference) and there no `url` or `description` fields.
May be there exists some undocumented fields but I do not know about it and did not see them in any other coveralls utils.

**Comment by starius** [comment]
There are two problems:
- [x] no link to a pull request,
- [ ] no link to AppVeyor build.

## no link to a pull request

There is a parameter `service_pull_request` in API. Can you use it? By the way I have no idea how coveralls finds pull request for Travis.

## no link to AppVeyor build

You [set](https://github.com/moteus/luacov-coveralls/blob/3b82df40f40e62558189c26999251ee123228a23/src/luacov/coveralls/CiInfo.lua#L31) `service_job_id = APPVEYOR_JOB_ID`.

I found the similar project for Python: https://github.com/coagulant/coveralls-python
Example: https://github.com/paylogic/pip-accel

They [use](https://github.com/coagulant/coveralls-python/blob/1a62ce2706ac73a521d231990e043886627bbf89/coveralls/api.py#L62) `service_job_id = APPVEYOR_BUILD_ID`.

However it doesn't work for them either: a coveralls [report](https://coveralls.io/builds/4009700) produced by AppVeyor contains no link to AppVeyor build page.

**Comment by ignacio** [comment]
@moteus The problem can be solved telling dkjson to use json.null as a value for nil.

``` lua
local json = require "dkjson"
local str = "[" .. ("null,"):rep(100) .. "0" .. (",null"):rep(100) .. "]"
local inp = assert(json.decode(str, nil, json.null))
local out = json.encode(inp):gsub("%s", "")
assert(str == out, out)
```

**Comment by moteus** [comment]
Try current master.
I fix decode `null` with dkjson and add `service_pull_request` to AppVeyor and CircleCI.
Thanx for tips.

**Comment by starius** [comment]
It fails: https://ci.appveyor.com/project/starius/lua-npge/build/job/vs5ajumm8420vhxv

**Comment by moteus** [comment]
You try use wrong url. 
You can just try `luarocks install luacov-coveralls --server=https://luarocks.org/dev`
or if you whant get from repo you have to use link to raw file.

**Comment by starius** [comment]
Fixed. The coveralls report produced by AppVeyor has a link to a pull request:
https://coveralls.io/builds/5092360
