### ISSUE TITLE
Invalid error report

### ISSUE THREAD

**Issue by thibaultcha** [moteus/luacov-coveralls#8]
Hi,

See this build (among others): https://travis-ci.org/thibaultcha/lua-resty-jit-uuid/builds/191860140

It seems it is encountering an error uploading the JSON file, but all 3 times, it seems we are printing the curl stdout instead of an actual error:
```
Uploading ...

Upload error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 16190  100    66  100 16124    111  27257 --:--:-- --:--:-- --:--:-- 31677

Raw data:	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 16190  100    66  100 16124    111  27257 --:--:-- --:--:-- --:--:-- 31677

--------------------

Upload error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 16190  100    66  100 16124     98  24170 --:--:-- --:--:-- --:--:-- 24246

Raw data:	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 16190  100    66  100 16124     98  24170 --:--:-- --:--:-- --:--:-- 24246

--------------------

Upload error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 16190  100    66  100 16124    183  44885 --:--:-- --:--:-- --:--:-- 45292

Raw data:	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 16190  100    66  100 16124    183  44885 --:--:-- --:--:-- --:--:-- 45292

--------------------

Uploading done
```

Maybe we could handle such a case properly and report the actual error, so then I could start working on fixing what's wrong with this build. This happened out of the blue on `0.2.1`, so I am unsure how to actually reproduce it, sorry.

**Comment by moteus** [comment]
Try install Lua-cURL library. In this case luacov-coveralls should use it. May be then you get more info.
Now it uses curl command line application and printout [output of command](https://github.com/moteus/luacov-coveralls/blob/master/src/luacov/coveralls/utils.lua#L117).
Basically it create tmp file and pass it as `--output` parameter and then read this file.

**Comment by thibaultcha** [comment]
Installing lua-cURL seems to result in a successful upload (no error at all). All in all, I wonder if this has to do with the newly added `-DLUAJIT_ENABLE_LUA52COMPAT` flag enabled by default in OpenResty `1.11.2.2` which would break code relying on `os.execute()` (and invoking curl from such a shell). I prefer relying on Lua-cURL anyways. Thanks for the tip!
