### ISSUE TITLE
Upload fails with LuaJIT compat52

### ISSUE THREAD

**Issue by fperrad** [moteus/luacov-coveralls#9]
Something goes wrong with a LuaJIT with Lua 5.2 compatibility mode.

LuaJIT 2.0.4 built with -DLUAJIT_ENABLE_LUA52COMPAT (see full log https://travis-ci.org/fperrad/lua-TestMore/jobs/210941900)
```
Upload error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 31380  100    66  100 31314    148  70494 --:--:-- --:--:-- --:--:-- 78481

Upload error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 31380  100    66  100 31314    200  95156 --:--:-- --:--:-- --:--:-- 96350

Upload error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 31380  100    66  100 31314    238   110k --:--:-- --:--:-- --:--:--  111k

```

Without LUAJIT_ENABLE_LUA52COMPAT that works fine (see full log https://travis-ci.org/fperrad/lua-TestMore/jobs/210941897).

```
Uploaded Job #88.7 to https://coveralls.io/jobs/23829992
```

Same issue with LuaJIT 2.1.0-beta2 (Job 88.10)

**Comment by moteus** [comment]
I think problem is when LuaJIT compiled with Lua 5.2 compat flags. (See #8)
Problem I think in [exec](https://github.com/moteus/luacov-coveralls/blob/master/src/luacov/coveralls/utils.lua#L88) function. 
Do such LuaJIT returns _VERSION as 5.2?

**Comment by fperrad** [comment]
LuaJIT always returns `Lua 5.1` as `_VERSION`.
